// <auto-generated />
using System;
using DeliveryService.API.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DeliveryService.API.Migrations
{
    [DbContext(typeof(DeliveryContext))]
    [Migration("20190410191510_firstmigration")]
    partial class firstmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DeliveryService.API.Model.Point", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Points");
                });

            modelBuilder.Entity("DeliveryService.API.Model.PointsConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cost");

                    b.Property<int?>("DestinationId");

                    b.Property<int?>("OriginId");

                    b.Property<int>("Time");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("OriginId");

                    b.ToTable("PointsConnection");
                });

            modelBuilder.Entity("DeliveryService.API.Model.PointsConnection", b =>
                {
                    b.HasOne("DeliveryService.API.Model.Point", "Destination")
                        .WithMany("Destinations")
                        .HasForeignKey("DestinationId");

                    b.HasOne("DeliveryService.API.Model.Point", "Origin")
                        .WithMany("Origins")
                        .HasForeignKey("OriginId");
                });
#pragma warning restore 612, 618
        }
    }
}
